version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  reviewers:
  - pranjalnadhani
  ignore:
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.1
    - 24.3.4
